--variables for pros
 local EasyMin = 0
 local MediumMin = 0
 local HardMin = 0
 local EasyMax = 0
 local MediumMax = 0
 local HardMax = 0
 local CurrentWaveNumber = 0

--settings for loosers
local WaveTextLabel = nil
local EasyNPCFolder = nil
local MediumNPCFolder = nil
local HardNPCFolder = nil
local BossNPC = nil
local MaxWaves = 10


--functions for optimization
local function SetupVars()
    local OneThirdWaves = MaxWaves/3
    local TwoThirdsWaves = (MaxWaves/3)*2
    local ThreeThirdsWaves = (MaxWaves/3)*3

end

local function LoadWave(WaveNumber)
    
end